version: "3.2"

services:
  mame:
    hostname: mame
    image: 927technology/mame:0.1
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    volumes:
      - /dev/snd:/dev/snd
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}:${HOME}
      - /etc/passwd:/etc/passwd


